package com.validatorbean;
// Generated Aug 22, 2019 3:41:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdminTable generated by hbm2java
 */
public class AdminTable  implements java.io.Serializable {


     private Integer adminId;
     private String adminPassword;
     private Set<ResultTable> resultTables = new HashSet<ResultTable>(0);

    public AdminTable() {
    }

	
    public AdminTable(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    public AdminTable(String adminPassword, Set<ResultTable> resultTables) {
       this.adminPassword = adminPassword;
       this.resultTables = resultTables;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    public Set<ResultTable> getResultTables() {
        return this.resultTables;
    }
    
    public void setResultTables(Set<ResultTable> resultTables) {
        this.resultTables = resultTables;
    }




}


