package com.validatorbean;
// Generated Aug 22, 2019 3:41:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ParticipantsInfo generated by hbm2java
 */
public class ParticipantsInfo  implements java.io.Serializable {


     private Integer participantsId;
     private String firstName;
     private String lastName;
     private char gender;
     private String phoneNumber;
     private String email;
     private Date dob;
     private String examTime;
     private String centre;
     private byte[] passport;
     private Set<ResultTable> resultTables = new HashSet<ResultTable>(0);

    public ParticipantsInfo() {
    }

	
    public ParticipantsInfo(String firstName, String lastName, char gender, String phoneNumber, String email, Date dob, String examTime, String centre, byte[] passport) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.dob = dob;
        this.examTime = examTime;
        this.centre = centre;
        this.passport = passport;
    }
    public ParticipantsInfo(String firstName, String lastName, char gender, String phoneNumber, String email, Date dob, String examTime, String centre, byte[] passport, Set<ResultTable> resultTables) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.dob = dob;
       this.examTime = examTime;
       this.centre = centre;
       this.passport = passport;
       this.resultTables = resultTables;
    }
   
    public Integer getParticipantsId() {
        return this.participantsId;
    }
    
    public void setParticipantsId(Integer participantsId) {
        this.participantsId = participantsId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getExamTime() {
        return this.examTime;
    }
    
    public void setExamTime(String examTime) {
        this.examTime = examTime;
    }
    public String getCentre() {
        return this.centre;
    }
    
    public void setCentre(String centre) {
        this.centre = centre;
    }
    public byte[] getPassport() {
        return this.passport;
    }
    
    public void setPassport(byte[] passport) {
        this.passport = passport;
    }
    public Set<ResultTable> getResultTables() {
        return this.resultTables;
    }
    
    public void setResultTables(Set<ResultTable> resultTables) {
        this.resultTables = resultTables;
    }




}


